services:
  finance-tracker:
    image: lxnet:finances
    container_name: finance-tracker
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
